// Complete list of countries with their ISO 3166-1 alpha-2 codes and continents
const countries = [
    // Africa (54)
    { name: 'Algeria', code: 'dz', continent: 'Africa' },
    { name: 'Angola', code: 'ao', continent: 'Africa' },
    { name: 'Benin', code: 'bj', continent: 'Africa' },
    { name: 'Botswana', code: 'bw', continent: 'Africa' },
    { name: 'Burkina Faso', code: 'bf', continent: 'Africa' },
    { name: 'Burundi', code: 'bi', continent: 'Africa' },
    { name: 'Cameroon', code: 'cm', continent: 'Africa' },
    { name: 'Cape Verde', code: 'cv', continent: 'Africa' },
    { name: 'Central African Republic', code: 'cf', continent: 'Africa' },
    { name: 'Chad', code: 'td', continent: 'Africa' },
    { name: 'Comoros', code: 'km', continent: 'Africa' },
    { name: 'Congo (Brazzaville)', code: 'cg', continent: 'Africa' },
    { name: 'Congo (Kinshasa)', code: 'cd', continent: 'Africa' },
    { name: 'Côte d\'Ivoire', code: 'ci', continent: 'Africa' },
    { name: 'Djibouti', code: 'dj', continent: 'Africa' },
    { name: 'Egypt', code: 'eg', continent: 'Africa' },
    { name: 'Equatorial Guinea', code: 'gq', continent: 'Africa' },
    { name: 'Eritrea', code: 'er', continent: 'Africa' },
    { name: 'Eswatini', code: 'sz', continent: 'Africa' },
    { name: 'Ethiopia', code: 'et', continent: 'Africa' },
    { name: 'Gabon', code: 'ga', continent: 'Africa' },
    { name: 'Gambia', code: 'gm', continent: 'Africa' },
    { name: 'Ghana', code: 'gh', continent: 'Africa' },
    { name: 'Guinea', code: 'gn', continent: 'Africa' },
    { name: 'Guinea-Bissau', code: 'gw', continent: 'Africa' },
    { name: 'Kenya', code: 'ke', continent: 'Africa' },
    { name: 'Lesotho', code: 'ls', continent: 'Africa' },
    { name: 'Liberia', code: 'lr', continent: 'Africa' },
    { name: 'Libya', code: 'ly', continent: 'Africa' },
    { name: 'Madagascar', code: 'mg', continent: 'Africa' },
    { name: 'Malawi', code: 'mw', continent: 'Africa' },
    { name: 'Mali', code: 'ml', continent: 'Africa' },
    { name: 'Mauritania', code: 'mr', continent: 'Africa' },
    { name: 'Mauritius', code: 'mu', continent: 'Africa' },
    { name: 'Morocco', code: 'ma', continent: 'Africa' },
    { name: 'Mozambique', code: 'mz', continent: 'Africa' },
    { name: 'Namibia', code: 'na', continent: 'Africa' },
    { name: 'Niger', code: 'ne', continent: 'Africa' },
    { name: 'Nigeria', code: 'ng', continent: 'Africa' },
    { name: 'Rwanda', code: 'rw', continent: 'Africa' },
    { name: 'Sao Tome and Principe', code: 'st', continent: 'Africa' },
    { name: 'Senegal', code: 'sn', continent: 'Africa' },
    { name: 'Seychelles', code: 'sc', continent: 'Africa' },
    { name: 'Sierra Leone', code: 'sl', continent: 'Africa' },
    { name: 'Somalia', code: 'so', continent: 'Africa' },
    { name: 'South Africa', code: 'za', continent: 'Africa' },
    { name: 'South Sudan', code: 'ss', continent: 'Africa' },
    { name: 'Sudan', code: 'sd', continent: 'Africa' },
    { name: 'Tanzania', code: 'tz', continent: 'Africa' },
    { name: 'Togo', code: 'tg', continent: 'Africa' },
    { name: 'Tunisia', code: 'tn', continent: 'Africa' },
    { name: 'Uganda', code: 'ug', continent: 'Africa' },
    { name: 'Zambia', code: 'zm', continent: 'Africa' },
    { name: 'Zimbabwe', code: 'zw', continent: 'Africa' },

    // Asia (50)
    { name: 'Afghanistan', code: 'af', continent: 'Asia' },
    { name: 'Armenia', code: 'am', continent: 'Asia' },
    { name: 'Azerbaijan', code: 'az', continent: 'Asia' },
    { name: 'Bahrain', code: 'bh', continent: 'Asia' },
    { name: 'Bangladesh', code: 'bd', continent: 'Asia' },
    { name: 'Bhutan', code: 'bt', continent: 'Asia' },
    { name: 'Brunei', code: 'bn', continent: 'Asia' },
    { name: 'Cambodia', code: 'kh', continent: 'Asia' },
    { name: 'China', code: 'cn', continent: 'Asia' },
    { name: 'Cyprus', code: 'cy', continent: 'Asia' },
    { name: 'Georgia', code: 'ge', continent: 'Asia' },
    { name: 'India', code: 'in', continent: 'Asia' },
    { name: 'Indonesia', code: 'id', continent: 'Asia' },
    { name: 'Iran', code: 'ir', continent: 'Asia' },
    { name: 'Iraq', code: 'iq', continent: 'Asia' },
    { name: 'Israel', code: 'il', continent: 'Asia' },
    { name: 'Japan', code: 'jp', continent: 'Asia' },
    { name: 'Jordan', code: 'jo', continent: 'Asia' },
    { name: 'Kazakhstan', code: 'kz', continent: 'Asia' },
    { name: 'Kuwait', code: 'kw', continent: 'Asia' },
    { name: 'Kyrgyzstan', code: 'kg', continent: 'Asia' },
    { name: 'Laos', code: 'la', continent: 'Asia' },
    { name: 'Lebanon', code: 'lb', continent: 'Asia' },
    { name: 'Malaysia', code: 'my', continent: 'Asia' },
    { name: 'Maldives', code: 'mv', continent: 'Asia' },
    { name: 'Mongolia', code: 'mn', continent: 'Asia' },
    { name: 'Myanmar', code: 'mm', continent: 'Asia' },
    { name: 'Nepal', code: 'np', continent: 'Asia' },
    { name: 'North Korea', code: 'kp', continent: 'Asia' },
    { name: 'Oman', code: 'om', continent: 'Asia' },
    { name: 'Pakistan', code: 'pk', continent: 'Asia' },
    { name: 'Palestine', code: 'ps', continent: 'Asia' },
    { name: 'Philippines', code: 'ph', continent: 'Asia' },
    { name: 'Qatar', code: 'qa', continent: 'Asia' },
    { name: 'Russia', code: 'ru', continent: 'Asia' },
    { name: 'Saudi Arabia', code: 'sa', continent: 'Asia' },
    { name: 'Singapore', code: 'sg', continent: 'Asia' },
    { name: 'South Korea', code: 'kr', continent: 'Asia' },
    { name: 'Sri Lanka', code: 'lk', continent: 'Asia' },
    { name: 'Syria', code: 'sy', continent: 'Asia' },
    { name: 'Taiwan', code: 'tw', continent: 'Asia' },
    { name: 'Tajikistan', code: 'tj', continent: 'Asia' },
    { name: 'Thailand', code: 'th', continent: 'Asia' },
    { name: 'Timor-Leste', code: 'tl', continent: 'Asia' },
    { name: 'Turkey', code: 'tr', continent: 'Asia' },
    { name: 'Turkmenistan', code: 'tm', continent: 'Asia' },
    { name: 'United Arab Emirates', code: 'ae', continent: 'Asia' },
    { name: 'Uzbekistan', code: 'uz', continent: 'Asia' },
    { name: 'Vietnam', code: 'vn', continent: 'Asia' },
    { name: 'Yemen', code: 'ye', continent: 'Asia' },

    // Europe (51)
    { name: 'Albania', code: 'al', continent: 'Europe' },
    { name: 'Andorra', code: 'ad', continent: 'Europe' },
    { name: 'Armenia', code: 'am', continent: 'Europe' },
    { name: 'Austria', code: 'at', continent: 'Europe' },
    { name: 'Azerbaijan', code: 'az', continent: 'Europe' },
    { name: 'Belarus', code: 'by', continent: 'Europe' },
    { name: 'Belgium', code: 'be', continent: 'Europe' },
    { name: 'Bosnia and Herzegovina', code: 'ba', continent: 'Europe' },
    { name: 'Bulgaria', code: 'bg', continent: 'Europe' },
    { name: 'Croatia', code: 'hr', continent: 'Europe' },
    { name: 'Cyprus', code: 'cy', continent: 'Europe' },
    { name: 'Czech Republic', code: 'cz', continent: 'Europe' },
    { name: 'Denmark', code: 'dk', continent: 'Europe' },
    { name: 'Estonia', code: 'ee', continent: 'Europe' },
    { name: 'Finland', code: 'fi', continent: 'Europe' },
    { name: 'France', code: 'fr', continent: 'Europe' },
    { name: 'Georgia', code: 'ge', continent: 'Europe' },
    { name: 'Germany', code: 'de', continent: 'Europe' },
    { name: 'Greece', code: 'gr', continent: 'Europe' },
    { name: 'Hungary', code: 'hu', continent: 'Europe' },
    { name: 'Iceland', code: 'is', continent: 'Europe' },
    { name: 'Ireland', code: 'ie', continent: 'Europe' },
    { name: 'Italy', code: 'it', continent: 'Europe' },
    { name: 'Kazakhstan', code: 'kz', continent: 'Europe' },
    { name: 'Kosovo', code: 'xk', continent: 'Europe' },
    { name: 'Latvia', code: 'lv', continent: 'Europe' },
    { name: 'Liechtenstein', code: 'li', continent: 'Europe' },
    { name: 'Lithuania', code: 'lt', continent: 'Europe' },
    { name: 'Luxembourg', code: 'lu', continent: 'Europe' },
    { name: 'Malta', code: 'mt', continent: 'Europe' },
    { name: 'Moldova', code: 'md', continent: 'Europe' },
    { name: 'Monaco', code: 'mc', continent: 'Europe' },
    { name: 'Montenegro', code: 'me', continent: 'Europe' },
    { name: 'Netherlands', code: 'nl', continent: 'Europe' },
    { name: 'North Macedonia', code: 'mk', continent: 'Europe' },
    { name: 'Norway', code: 'no', continent: 'Europe' },
    { name: 'Poland', code: 'pl', continent: 'Europe' },
    { name: 'Portugal', code: 'pt', continent: 'Europe' },
    { name: 'Romania', code: 'ro', continent: 'Europe' },
    { name: 'Russia', code: 'ru', continent: 'Europe' },
    { name: 'San Marino', code: 'sm', continent: 'Europe' },
    { name: 'Serbia', code: 'rs', continent: 'Europe' },
    { name: 'Slovakia', code: 'sk', continent: 'Europe' },
    { name: 'Slovenia', code: 'si', continent: 'Europe' },
    { name: 'Spain', code: 'es', continent: 'Europe' },
    { name: 'Sweden', code: 'se', continent: 'Europe' },
    { name: 'Switzerland', code: 'ch', continent: 'Europe' },
    { name: 'Turkey', code: 'tr', continent: 'Europe' },
    { name: 'Ukraine', code: 'ua', continent: 'Europe' },
    { name: 'United Kingdom', code: 'gb', continent: 'Europe' },
    { name: 'Vatican City', code: 'va', continent: 'Europe' },

    // North America (41)
    { name: 'Antigua and Barbuda', code: 'ag', continent: 'North America' },
    { name: 'Bahamas', code: 'bs', continent: 'North America' },
    { name: 'Barbados', code: 'bb', continent: 'North America' },
    { name: 'Belize', code: 'bz', continent: 'North America' },
    { name: 'Canada', code: 'ca', continent: 'North America' },
    { name: 'Costa Rica', code: 'cr', continent: 'North America' },
    { name: 'Cuba', code: 'cu', continent: 'North America' },
    { name: 'Dominica', code: 'dm', continent: 'North America' },
    { name: 'Dominican Republic', code: 'do', continent: 'North America' },
    { name: 'El Salvador', code: 'sv', continent: 'North America' },
    { name: 'Grenada', code: 'gd', continent: 'North America' },
    { name: 'Guatemala', code: 'gt', continent: 'North America' },
    { name: 'Haiti', code: 'ht', continent: 'North America' },
    { name: 'Honduras', code: 'hn', continent: 'North America' },
    { name: 'Jamaica', code: 'jm', continent: 'North America' },
    { name: 'Mexico', code: 'mx', continent: 'North America' },
    { name: 'Nicaragua', code: 'ni', continent: 'North America' },
    { name: 'Panama', code: 'pa', continent: 'North America' },
    { name: 'Saint Kitts and Nevis', code: 'kn', continent: 'North America' },
    { name: 'Saint Lucia', code: 'lc', continent: 'North America' },
    { name: 'Saint Vincent and the Grenadines', code: 'vc', continent: 'North America' },
    { name: 'Trinidad and Tobago', code: 'tt', continent: 'North America' },
    { name: 'United States', code: 'us', continent: 'North America' },

    // South America (14)
    { name: 'Argentina', code: 'ar', continent: 'South America' },
    { name: 'Bolivia', code: 'bo', continent: 'South America' },
    { name: 'Brazil', code: 'br', continent: 'South America' },
    { name: 'Chile', code: 'cl', continent: 'South America' },
    { name: 'Colombia', code: 'co', continent: 'South America' },
    { name: 'Ecuador', code: 'ec', continent: 'South America' },
    { name: 'Guyana', code: 'gy', continent: 'South America' },
    { name: 'Paraguay', code: 'py', continent: 'South America' },
    { name: 'Peru', code: 'pe', continent: 'South America' },
    { name: 'Suriname', code: 'sr', continent: 'South America' },
    { name: 'Uruguay', code: 'uy', continent: 'South America' },
    { name: 'Venezuela', code: 've', continent: 'South America' },

    // Oceania (27)
    { name: 'Australia', code: 'au', continent: 'Oceania' },
    { name: 'Fiji', code: 'fj', continent: 'Oceania' },
    { name: 'Kiribati', code: 'ki', continent: 'Oceania' },
    { name: 'Marshall Islands', code: 'mh', continent: 'Oceania' },
    { name: 'Micronesia', code: 'fm', continent: 'Oceania' },
    { name: 'Nauru', code: 'nr', continent: 'Oceania' },
    { name: 'New Zealand', code: 'nz', continent: 'Oceania' },
    { name: 'Palau', code: 'pw', continent: 'Oceania' },
    { name: 'Papua New Guinea', code: 'pg', continent: 'Oceania' },
    { name: 'Samoa', code: 'ws', continent: 'Oceania' },
    { name: 'Solomon Islands', code: 'sb', continent: 'Oceania' },
    { name: 'Tonga', code: 'to', continent: 'Oceania' },
    { name: 'Tuvalu', code: 'tv', continent: 'Oceania' },
    { name: 'Vanuatu', code: 'vu', continent: 'Oceania' },

    // Antarctica (No permanent population, but included for completeness)
    { name: 'Antarctica', code: 'aq', continent: 'Antarctica' },

    // Other territories and regions (Not sovereign countries but included for completeness)
    { name: 'American Samoa', code: 'as', continent: 'Oceania' },
    { name: 'Aruba', code: 'aw', continent: 'North America' },
    { name: 'Bermuda', code: 'bm', continent: 'North America' },
    { name: 'British Virgin Islands', code: 'vg', continent: 'North America' },
    { name: 'Cayman Islands', code: 'ky', continent: 'North America' },
    { name: 'Cook Islands', code: 'ck', continent: 'Oceania' },
    { name: 'Curaçao', code: 'cw', continent: 'North America' },
    { name: 'Falkland Islands', code: 'fk', continent: 'South America' },
    { name: 'Faroe Islands', code: 'fo', continent: 'Europe' },
    { name: 'French Guiana', code: 'gf', continent: 'South America' },
    { name: 'French Polynesia', code: 'pf', continent: 'Oceania' },
    { name: 'Gibraltar', code: 'gi', continent: 'Europe' },
    { name: 'Greenland', code: 'gl', continent: 'North America' },
    { name: 'Guadeloupe', code: 'gp', continent: 'North America' },
    { name: 'Guam', code: 'gu', continent: 'Oceania' },
    { name: 'Guernsey', code: 'gg', continent: 'Europe' },
    { name: 'Hong Kong', code: 'hk', continent: 'Asia' },
    { name: 'Isle of Man', code: 'im', continent: 'Europe' },
    { name: 'Jersey', code: 'je', continent: 'Europe' },
    { name: 'Macau', code: 'mo', continent: 'Asia' },
    { name: 'Martinique', code: 'mq', continent: 'North America' },
    { name: 'Mayotte', code: 'yt', continent: 'Africa' },
    { name: 'Montserrat', code: 'ms', continent: 'North America' },
    { name: 'New Caledonia', code: 'nc', continent: 'Oceania' },
    { name: 'Niue', code: 'nu', continent: 'Oceania' },
    { name: 'Norfolk Island', code: 'nf', continent: 'Oceania' },
    { name: 'Northern Mariana Islands', code: 'mp', continent: 'Oceania' },
    { name: 'Puerto Rico', code: 'pr', continent: 'North America' },
    { name: 'Réunion', code: 're', continent: 'Africa' },
    { name: 'Saint Barthélemy', code: 'bl', continent: 'North America' },
    { name: 'Saint Martin', code: 'mf', continent: 'North America' },
    { name: 'Saint Pierre and Miquelon', code: 'pm', continent: 'North America' },
    { name: 'Sint Maarten', code: 'sx', continent: 'North America' },
    { name: 'South Georgia and the South Sandwich Islands', code: 'gs', continent: 'Antarctica' },
    { name: 'Svalbard and Jan Mayen', code: 'sj', continent: 'Europe' },
    { name: 'Tokelau', code: 'tk', continent: 'Oceania' },
    { name: 'Turks and Caicos Islands', code: 'tc', continent: 'North America' },
    { name: 'U.S. Virgin Islands', code: 'vi', continent: 'North America' },
    { name: 'Wallis and Futuna', code: 'wf', continent: 'Oceania' },
    { name: 'Western Sahara', code: 'eh', continent: 'Africa' }
];

// The countries array is now available globally for use in other scripts
